#!/usr/bin/env bash

# optional argument handling
if [[ "$1" == "version" ]]
then
  echo "1.0.0"
  exit 0
fi

# optional argument handling
if [[ "$1" == "config" ]]
then
  echo "$KUBECONFIG"
  exit 0
fi

echo "I am a plugin named kubectl-foo"

echo ""
echo "cli parameters:"
#echo $@
for i; do 
  echo $i 
done

echo ""
echo "FOO: $FOO"

echo ""
echo "end of plugin"
